default:
  components:
    sidebar1: [user, topUsers]
    sidebar2: [user, topModUsers]
    sidebar3: []
    sidebar4: []
    sidebar5: []
    sidebar6: []
    sidebar7: []

authRequired:
  has_layout: false